### ISSUE TITLE
Interactive datavis

### ISSUE THREAD

**Issue by hugobowne** [hugobowne/COVID-19-EDA-tutorial#6]
hey @paras009 

i was planning on building an interactive datavis next for this tutorial.

I was thinking of using bokeh: https://docs.bokeh.org/en/latest/index.html

it could be used in conjunction with holoviews: http://holoviews.org/user_guide/Plotting_with_Bokeh.html

or we could could use altair: https://altair-viz.github.io/ 

do you have experience with any of these? or any thoughts on this?

**Comment by paras009** [comment]
Hey @hugobowne, that's really an amazing idea. I have a little bit experience in working in these. I have worked with Bokeh earlier and I have worked on a few visualization tools like Superset and Tableau as well.
I would love to assist you in the building process!

**Comment by hugobowne** [comment]
@paras009 awesome. excuse the delay here -- i have actually flown nyc --> sydney to be closer to family. i'm now somewhat settled.

i'll play around with some of these tools tomorrow. then i'll share some code. feel free to do the same -- 

im thinking of creating an interactive vis something like the first one here: https://www.nytimes.com/interactive/2020/03/21/upshot/coronavirus-deaths-by-country.html

**Comment by hugobowne** [comment]
@paras009 I've now got some super basic interactive plots using bokeh & altair at bottom of this notebook/branch: https://github.com/hugobowne/COVID-19-EDA-tutorial/blob/interactive_plots/notebooks/1-COVID-19-EDA-solution.ipynb


`environment.yml` doesn't have the necessary installs yet but executing

```
conda install bokeh
conda install conda install -c conda-forge altair vega_datasets
```
after activating the env will do the trick

what i want to get is something similar to the first interactive plot in [this nytimes article](https://www.nytimes.com/interactive/2020/03/21/upshot/coronavirus-deaths-by-country.html)

notice that my altair plot has 

- a different coloured line for each country and 
- a hover tool that tells you the country when you hover over the line (you need to do it quite precisely, though).

this is what I'd like to be able to do in bokeh. in the final figure so far, I have plotted all the lines, but without hover tools and different colours. Could you see if you can get these up and running in bokeh here?

**Comment by paras009** [comment]
Sure @hugobowne, will do it!

**Comment by hugobowne** [comment]
Awesome! I've just split the bokeh stuff out from the altair so bokeh is all at the bottom of the NB now.

i've had some fun with altair and made charts that are more interactive now. check out the 2nd chart under altair and click on any curve to make it stand out! Still a WIP tho ofc

**Comment by hugobowne** [comment]
I've done a lot of work on the Altair figures for this week's live coding session so I'm going to close this issue. @paras009 feel free to open another or a PR in a different NB for Bokeh at any point.
